proxy:
  replicaCount: 1
  image:
    repository: phantomproxy
    tag: "13.0"
  service:
    port: 443
  ingress:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: phantom
    password: phantom
    database: phantom

redis:
  enabled: true
