apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phantomproxy.fullname" . }}-config
  labels:
    {{- include "phantomproxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    bind_ip: "0.0.0.0"
    https_port: {{ .Values.config.httpsPort }}
    domain: {{ .Values.config.domain }}
    cert_path: "./certs/cert.pem"
    key_path: "./certs/key.pem"
    database_path: "./phantom.db"
    api_enabled: true
    api_port: {{ .Values.config.apiPort }}
    debug: {{ .Values.config.debug }}
